In [16]:
from rdflib import Graph

import pandas as pd
import requests

In [8]:
# This is sourced from the RDF tutorial
# Pros: No fixed schema -- established based on schema, can query any variety of data sets in the wikidata knowledge base.
# Cons: Difficult to learn and interpret as a beginner. This is a very limited tutorial set, since I need to develop more fluency with this form. The volume of domains to query means, that there are many examples but not all are easy to adapt to a unique usage.

# Create a Graph, parse in Internet data
g = Graph().parse("http://www.w3.org/People/Berners-Lee/card")

# Query the data in g using SPARQL
# This query returns the 'name' of all `foaf:Person` instances
q = """
    PREFIX foaf: <http://xmlns.com/foaf/0.1/>

    SELECT ?name
    WHERE {
        ?p rdf:type foaf:Person .

        ?p foaf:name ?name .
    }
"""

# Apply the query to the graph and iterate through results
for r in g.query(q):

    print(r["name"])

Timothy Berners-Lee

In [18]:
# File download, read locally. Source: https://www.kaggle.com/datasets/mattop/new-york-city-bus-breakdown-and-delays?resource=download
# Pros: This approach can be executed without an internet connection, is extremely accessible once the file is in the correct place. Data can be inspected independently without having to pass through an API or endpoint.
# Cons: The entire dataset has to be available to be loaded in memory for a local machine, which can be impossible to manage with very large files. The file also cannot be accessed by any machine, only from the computer it's currently stored on (directly, or by ssh-ing in)
df = pd.read_csv("./data/bus-breakdowns-delays.csv")
filtered = df[["How_Long_Delayed", "Reason"]]
filtered.dropna(subset=["How_Long_Delayed"], inplace=True)
filtered.head()

  How_Long_Delayed         Reason
1            20MNS  Heavy Traffic
2            15MIN  Heavy Traffic
3           15 MIN  Heavy Traffic
5           30 min  Heavy Traffic
6           20MINS  Heavy Traffic

In [14]:
# JSON API, Source: https://data.seattle.gov/Transportation/Fremont-Bridge-Bicycle-Counter/65db-xm6k/about_data
# Pros: This is a publicly available API, providing easily readable and structured data. JSON translates very easily to a pandas dataframe and can (but not always) be used with minimal normalization or reformatting.
# Cons: In this case the JSON format was very flat, but it could have been much more nested, or complex, which would then require normalization and interpretation work. Any filtering or selection has to be done once the initial dataset or subset is loaded in memory. In this case, selecting a for a subset of data wasn't available.

url = "https://data.seattle.gov/resource/65db-xm6k.json"

response = requests.get(url=url)
r = response.json()
df = pd.DataFrame.from_dict(r)
df.head()

                      date fremont_bridge fremont_bridge_nb fremont_bridge_sb
0  2026-03-31T23:00:00.000             22                18                 4
1  2026-03-31T22:00:00.000             54                34                20
2  2026-03-31T21:00:00.000             76                47                29
3  2026-03-31T20:00:00.000             67                31                36
4  2026-03-31T19:00:00.000            170               120                50